### ISSUE TITLE
Оператор sms4b.ru

### ISSUE THREAD

**Issue by asosnoviy** [oscript-library/messenger#1]
У меня в организации используют sms4b.ru.    
Хочу добавить поддержку.

**Comment by EvilBeaver** [comment]
Отлично! По готовности присылайте пулреквест!

**Comment by asosnoviy** [comment]
@EvilBeaver вот же он https://github.com/oscript-library/messenger/pull/2
Может я что то не так сделал и его не видно?

**Comment by EvilBeaver** [comment]
Нет, это я спросонья не разглядел )

**Comment by asosnoviy** [comment]
На всякий случай перепроверил  Slack и sms4b работают с OneScript-1.0.14
