### ISSUE TITLE
Как использовать телеграмм?

### ISSUE THREAD

**Issue by averyanovalex** [oscript-library/messenger#28]
Как использовать телеграмм? 
Из документации я этого не понял.

Я же правильно понял, что при отправке сообщения, мне нужно знать:
1.токен бота
2.ID чата?
3.Библиотека сам работает через динамические прокси и мне заморачиваться из РФ не надо?

Ниже код, но ничего не отправляет
Подскажите, где ошибся?

#Использовать messenger
Токен ="ХХХХХ";

Мессенджер = Новый Мессенджер();
Мессенджер.ИнициализироватьТранспорт("telegram", Новый Структура("Логин", Токен));

Сообщение = "Что-то пошло не так"; //сообщение как просто текст
Мессенджер.ОтправитьСообщение("telegram", "37096761", Сообщение);

**Comment by k2589** [comment]
Привет! Библиотека версии 2.0.8?

**Comment by averyanovalex** [comment]
Библиотека 2.0.8
ID взял оттуда.
Ничего не происходит. Ошибку не возвращает. Кидаю код.
Это тестовый бот. Можно юзать. Токен потом перевыпущу


===== СКРИПТ =====
#Использовать messenger
Токен ="856103532:AAGO4WmsYd575u54qlWjdLyOP_ZRyhDAzLU";

//https://api.telegram.org/bot856103532:AAGO4WmsYd575u54qlWjdLyOP_ZRyhDAzLU/getupdates

Мессенджер = Новый Мессенджер();
Мессенджер.ИнициализироватьТранспорт("telegram", Новый Структура("Логин", Токен));

Сообщение = "Что-то пошло не так"; //сообщение как просто текст
Мессенджер.ОтправитьСообщение("telegram", "37096761", Сообщение);

Сообщить("Я отработал");

==== UPDATE с ТЕЛЕГРАММА  =====
{"ok":true,"result":[{"update_id":60643510,
"message":{"message_id":87,"from":{"id":370967617,"is_bot":false,"first_name":"\u0410\u043b\u0435\u043a\u0441\u0435\u0439","last_name":"\u0410\u0432\u0435\u0440\u044c\u044f\u043d\u043e\u0432","username":"alex_averyanov","language_code":"ru"},"chat":{"id":370967617,"first_name":"\u0410\u043b\u0435\u043a\u0441\u0435\u0439","last_name":"\u0410\u0432\u0435\u0440\u044c\u044f\u043d\u043e\u0432","username":"alex_averyanov","type":"private"},"date":1574841396,"text":"hi"}}]}

**Comment by asosnoviy** [comment]
Мессенджер.ОтправитьСообщение("telegram", "37096761", Сообщение);
"id":370967617,"
Циферы 7 нехватает

**Comment by averyanovalex** [comment]
Да, верно! Не хватает.
Но результат тот же. Скрипт отрабатывает без ошибок.
Но в бот ничего не приходит.

**Comment by averyanovalex** [comment]
Все агонь! получилось. Спасибо за хелп ;)
