### ISSUE TITLE
Отправка сообщения в gitter

### ISSUE THREAD

**Issue by asosnoviy** [oscript-library/messenger#5]
Хочется отправлять сообщения в gitter.  
Что бы оповещать сообщество о появлении релизов в хабе.

**Comment by asosnoviy** [comment]
У gittera своя интеграция с чем угодно   
![image](https://cloud.githubusercontent.com/assets/15638529/23091811/abf56df2-f5cf-11e6-840a-f900a9ea19d8.png)

Но иногда хочется из CLI

**Comment by asosnoviy** [comment]
Сейчас могу предложить отправку в комнату по id, по пользовательскому токену.  
Минусы: нужно регать "юзер-бота".  
Плюсы: Можно прямо сейчас добавить.  

P.S. Я не представляю как это покрывать тестами.   
Точнее представляю, но тогда утечет токен.  
Без токена, получим 401 HTTP.

**Comment by nixel2007** [comment]
@asosnoviy да, вполне подойдёт. 
Так то можно и под своей учеткой спамить :)

**Comment by nixel2007** [comment]
А тестировать - никто не отменял секретные переменные среды на ci

**Comment by nixel2007** [comment]
Ну или мокать хттп сервис

**Comment by asosnoviy** [comment]
Тесты есть, но или задавать переменный окружения, или в тексте теста для локальной проверки. При пустых значениях  тесты будут пропускаться.
